### PR TITLE
Expose direct polar/azimuthal angle controls

### PR DESCRIPTION
**Pull request by haywirez**
### Why

Added additional setters to `OrbitControls` that allow setting the polar / azimuthal angles directly. This allows for programmatic control like:

```ts
  // ...
  const myCamera = useRef<PerspectiveCamera>();
  const controls = useRef<OrbitControls>();

  useFrame(() => {
    const angle = 0.42; // get current value from whatever (animation) state
    controls.current?.setAzimuthalAngle(angle);
  }, 1);

  return (
    <>
      <OrbitControls enabled={false} camera={myCamera.current} ref={controls} />
      <PerspectiveCamera ref={myCamera} position={[0, 5, 5]} />
    </>
  );

```

This "quick & dirty" implementation is based on a code snippet from @drcmda to always converts to the shortest delta angle give the current position. Would appreciate some eyes as this might be yet simplified, but it did the job for me so far.

### Checklist

- [ ] Documentation updated
- [ ] Storybook entry added
- [ ] Ready to be merged

### CODE REVIEW

**Comment by joshuaellis** [comment]
Huge thanks for this contribution! ⭐ 

Would you be able to make a storybook for this? It A. helps test what you've created & B. helps keep an eye on regressions as the library matures.

**Comment by haywirez** [comment]
(Note that `enabled: false` is needed on `OrbitControls`)

**Review by joshuaellis — APPROVED** [review]
Thanks for the feature!

I'll be honest about Storybook, i've sort of hacked it but it's really not ideal at all as a tool. I'm wondering if there's a better way to manage these sorts of things, ideally I want to avoid using `react` for the demonstrating of components but it doesn't seem like there's a very good solution out there.

The reason it is the way it is, is because `three` requires finding the correct dom element, which in storybook's instance is inside an iframe so it isn't accessible until mount – hence the `useEffect` hook. But then you run into issues where controls cause entire rerenders – not ideal... 🤔

**Comment by drcmda** [comment]
@haywirez great news, completely missed it, is it possible to animate the movement?

**Comment by haywirez** [comment]
@drcmda yes, still not ideal, but it worked well enough for now... Keep in mind that the angle changes are still "throttled" by the [`dampingFactor`](https://github.com/pmndrs/three-stdlib/blob/main/src/controls/OrbitControls.ts#L49) in the internals — so the positioning it's not 100% accurate — unless disabled.

**Pull request merged**
