### PR TITLE
fix: GLTFLoader check if texture is null

### PR DESCRIPTION
**Pull request by zaesur**
### Why
GLTFLoader is out of sync with three/examples/jsm; a null check was added to GLTFLoader to ensure that a model with missing/corrupt textures can still load.

### What
Copied code from three/examples/jsm

### Checklist

- [x] Ready to be merged

### CODE REVIEW

**Comment by zaesur** [comment]
Hello; this is my first contribution to a public project.

I discovered this issue when a client's asset could not be loaded on our application, but could be partially rendered by an online GLTF viewer that was using three/examples/jsm. I have tracked down this update to [this PR](https://github.com/mrdoob/three.js/pull/25014). The proposed PR merely sync's GLTFLoader with the changes made in the main three repository.

I have done my best to read and follow contributing guidelines - please reach out in case if I made any mistakes.

**Comment by drcmda** [comment]
isn't this a bug in three js though? @zaesur @CodyJasonBennett 

the library should absolutely not just skip over a missing texture like that, it must in my opinion crash. otherwise errors can't even be caught.

**Comment by drcmda** [comment]
i would prefer 

```jsx
const loader = new GLTFLoader()
loader.ignoreErrors = true
```

this way we have error response and gltf can still be unit tested. while viewer-type projects can just plow on.

**Comment by zaesur** [comment]
hey - i completely understand the apprehension behind allowing missing textures.

unfortunately, i am encountering precisely the situation sketched in the linked discussions, namely that clients still expect their faulty models to be partially loaded. for better or worse, i need to load the model without those textures, and besides using three-stdlib or the examples module, my only option would be to write a custom loader to allow that kind of behaviour.

i like the idea of adding a sort of 'strict' flag, as you mention, but i'm concerned about fiber's 'useLoader' hook, which uses a loader _prototype_ as an argument. i'm not familiar enough with that library to tell if supplying an instantiated loader (with the flag set) would still work.

**Comment by drcmda** [comment]
> hey - i completely understand the apprehension behind allowing missing textures.
> 
> unfortunately, i am encountering precisely the situation sketched in the linked discussions, namely that clients still expect their faulty models to be (partially) loaded. for better or worse, i need to load the model without those textures, and besides using three-stdlib or the examples module, my only option would be to write a custom loader to allow that kind of behaviour.
> 
> i like the idea of adding a sort of 'strict' flag, as you mention, but i'm concerned about fiber's 'useLoader' hook, which uses a loader _prototype_ as an argument. i'm not familiar enough with that library to tell if supplying an instantiated loader (with the flag set) would still work.

if would be the same in react

```jsx
const result = useLoader(GLTFLoader, url, loader => {
  loader.ignoreErrors = true
})
```

you can do the same with useGLTF.

**Comment by zaesur** [comment]
that seems reasonable, i completely missed the obvious way to set that flag.

given the discussion going on over three/jsm, perhaps best to wait how that pans out? without expressing preference for either route, i'd still expect both projects to be functionally equivalent (meaning three-stdlib adopts the same permissiveness, or whatever outcome of that discussion).

the three-stdlib community would then be free to implement a validator, or a 'strict' loader, without giving up on alignment between projects.

**Comment by drcmda** [comment]
i do not expect an outcome tbh. i've seen these discussions a thousand times and once something has been merged it is set in stone. the discussion in both threads now just goes "we have decided" and this will turn bitter if goes on, so i've muted it.

we have made stdlib for that very reason, so they can't break make a rug pull and break the eco system (or testing in this case). 😅 an ignore flag seems reasonable to me, and we can rename if they really do it but name it differently. these are imo edges, just their pr, it wasn't documented and i found out bc of you.

**Pull request closed without merging**
