### PR TITLE
Feature/dicussion#1735 reverse orbit

### PR DESCRIPTION
**Pull request by dotesfera**
### Why

Because there are users that feel more comfortable orbiting left->right = turns left.

### What

Added reverseOrbit boolean to OrbitControls.ts

### Checklist

- [ ] Documentation updated
- [ ] Storybook entry added
- [ ] Ready to be merged

### CODE REVIEW

**Comment by drcmda** [comment]
are the CI errors due to this pr or is it a general problem @joshuaellis

**Comment by joshuaellis** [comment]
its a problem with the PR.

**Comment by dotesfera** [comment]
What have I done wrong?

**Comment by shuta13** [comment]
@dotesfera 

Delete `)` from https://github.com/dotesfera/three-stdlib/blob/4983f21a9e3dc0a207b14910e2b39efc9ebf1ea8/src/loaders/TiltLoader.js#L446

This CI errors are caused by the syntax error.

**Comment by dotesfera** [comment]
Sorry for the delay, i think now it's fixed.

**Comment by dotesfera** [comment]
Is someone to aprove the PR's?

**Comment by joshuaellis** [comment]
Can you explain the change to TiltLoader? It would break node environments because you're calling a loader in global space.

**Comment by dotesfera** [comment]
> Can you explain the change to TiltLoader? It would break node environments because you're calling a loader in global space.

I don't know what happened there, as initially I edited a completely different file...Maybe because of my lint plugin?
Can you please fix that? I just want to add the reverse orbit feature.

**Comment by dotesfera** [comment]
Hi, can this be accepted?

**Comment by joshuaellis** [comment]
No there's changes in TiltLoader which will break SSR. They need to be removed before please.

**Comment by dotesfera** [comment]
How about now?

**Review by joshuaellis — APPROVED** [review]
Looks good! Thanks for the contribution ⭐

**Comment by dotesfera** [comment]
Thanks, when can we have these changes reflected on react three fiber?

**Comment by joshuaellis** [comment]
> Thanks, when can we have these changes reflected on react three fiber?

Do you mean `drei`? you'd have to make a PR there.

**Comment by dotesfera** [comment]
Ah ok, thanks.

**Pull request merged**
