### PR TITLE
fix: controls event dispatcher types

### PR DESCRIPTION
**Pull request by RodrigoHamuy**
Fixes:
- #387

### CODE REVIEW

**Comment by abernier** [comment]
hi @RodrigoHamuy, I've just tried upgrading drei to latest three-stdlib but I have TS warnings:

image

**Comment by RodrigoHamuy** [comment]
Hi @abernier, really sorry about that.

I probably need some help as I am not sure what should we do. This PR made a copy of `EventListener` that `three-stdlib` uses for their controls, as the original one introduced a breaking change in their typings ([link](https://github.com/three-types/three-ts-types/releases/tag/r168)) as mentioned in this [issue](https://github.com/pmndrs/three-stdlib/issues/387).

But in reality the original `EventListener` hasn't change in 3 years, only their typings got more restrictive since r168.

My understanding is that because `three-stdlib` aims as having backwards compatibility, we can't just upgrade to use the latest `@types/three`, but without doing all `three-stdlib` controls event listeners types will be `never`. This is what this PR attempted at fixing.

Is there another way to do this? I will have a play on my side too, but not really sure we can do anything else apart from actually asking `@types/three` to revert that change and allow loosely types again ( https://github.com/three-types/three-ts-types/pull/1145 ).

Maybe we should revert this commit in the meantime, sorry for the trouble.

CC @CodyJasonBennett

**Comment by CodyJasonBennett** [comment]
I believe that type error comes from R3F since now the types diverge. Maybe we can loosen it there.

https://github.com/pmndrs/react-three-fiber/blob/5a5080056fa00e81dba2e1cb922e9875ea545e48/packages/fiber/src/core/store.ts#L112

**Comment by CodyJasonBennett** [comment]
All we need is a small interface that is compatible with both types, although it doesn't matter whether `controls` emits events or not. It's an implementation detail of three's existing controls, but not user-land. It's possible we can loosen it to a very small interface.

**Comment by RodrigoHamuy** [comment]
> hi @RodrigoHamuy, I've just tried upgrading drei to latest three-stdlib but I have TS warnings:
> 
> image

Is there a way to replicate these errors? I missed this because on my project at least everything is working OK after upgrading.

**Comment by abernier** [comment]
@RodrigoHamuy 

yes, if you clone pmndrs/drei @ master and `yarn add three-stdlib@latest`, then `yarn typecheck`

you should have the same TS errors

@CodyJasonBennett like this?:

in `pmndrs/react-three-fiber/blob/master/packages/fiber/src/core/store.ts`:
```diff
- controls: THREE.EventDispatcher;
+ controls: Omit<THREE.EventDispatcher, 'addEventListener' | 'hasEventListener' | "removeEventListener"> | null;
```

if I understand correctly, this means a user can no longer `controls = useThree(state => state.controls); controls.addEventListener(...)` without a TS error? -- because, this is considered private methods?

**Comment by abernier** [comment]
oh silly me i haven't noticed my Omit type is equivalent to `{}` since [THREE.EventDispatcher](https://github.com/mrdoob/three.js/blob/master/src/core/EventDispatcher.js) has nothing to offer more than those 4 methods

**Comment by RodrigoHamuy** [comment]
@CodyJasonBennett @abernier here are a few ideas:

- My personal favourite, revert those changes from `@types/three`: https://github.com/three-types/three-ts-types/pull/1398
- Otherwise this would work but requires a small change in `drei`: https://github.com/pmndrs/three-stdlib/pull/392

I prefer option one, is simple and avoids having to maintain a copy of a class that hasn't changed in years (`EventDispatcher`) in `three-stdlib`.

Happy to also show a draft PR of `drei` changes if interested in option two?

Mainly I believe is just in https://github.com/RodrigoHamuy/drei/blob/master/src/core/OrbitControls.tsx#L7

```diff
- export type OrbitControlsChangeEvent = Event & {
-   target: EventTarget & { object: Camera }
- }
+ export type OrbitControlsChangeEvent = Parameters<OrbitControlsImpl['addEventListener']>[1]
```

**Comment by tamighi** [comment]
I see that the transformControls is a bit more tricky as copying the native three implementation would require to put a lot of transformControls property to public so that it's "transformControlsRoot" has access to them.

https://github.com/mrdoob/three.js/blob/0f523acc5a1d6ae3d4d02a41f5d4793adc9303d5/examples/jsm/controls/TransformControls.js#L763

**Comment by RodrigoHamuy** [comment]
@CodyJasonBennett @abernier any thoughts on the 2 alternative solutions mentioned [here](https://github.com/pmndrs/three-stdlib/pull/388#issuecomment-2539188178)? Neither of them would require changing `react-three-fiber`. Option 1 (revert @types/three to a more loosen typing) means also revert this PR, which I still think is the easiest, cleanest solution.

**Comment by abernier** [comment]
iiuc 1. depends on https://github.com/three-types/three-ts-types/pull/1398, whether it is merged or not, is that it?

**Comment by abernier** [comment]
i mean: it's not possible to revert if https://github.com/three-types/three-ts-types/pull/1398 is not merged, am i right?

**Comment by CodyJasonBennett** [comment]
Maybe let's open an issue since a revert is unlikely (it is equally breaking to change your mind), and we'd all be interested in a workaround or proper migration. I still think loosening the type on R3F's side would be the best course of action since we don't actually care about controls implementing events at all. It can extend as simple as an opaque object type.

**Comment by CodyJasonBennett** [comment]
I meant either an opaque type that implemented event listener methods without generics or an object like that. This still might be too strict since people may implement their own interface with parameters; again, I think `controls` both shouldn't be in R3F to begin with, and the type being an irrelevant and inconsistent constraint—assuming that all controls follow three/examples, which is certainly not the case.

```diff
// file: https://github.com/pmndrs/react-three-fiber/blob/master/packages/fiber/src/core/store.ts#L112
- controls: THREE.EventDispatcher | null
+ controls: {
+   addEventListener(type: string, listener: (...args: any[]) => void): void
+   hasEventListener(type: string, listener: (...args: any[]) => void): boolean
+   removeEventListener(type: string, listener: (...args: any[]) => void): void
+   dispatchEvent(event: any): void
+} | null
```

If #392 can create a compatible overload, then let's roll with that. Still, I'm unhappy with R3F taking such opinions over user code.

**Comment by RodrigoHamuy** [comment]
@CodyJasonBennett fair enough. In that case I leave it with you to decide between these (I didn't added the loosing types of the `R3F` store because I'm worried it will snowball this bug even more):

- **option A**
   https://github.com/pmndrs/three-stdlib/pull/392
   **+**
   https://github.com/pmndrs/drei/pull/2276
- **option B**
  https://github.com/three-types/three-ts-types/pull/1398
  **+**
  **revert** https://github.com/pmndrs/three-stdlib/pull/388

My personal preference is still option b since it reduces bundle size (we don't need to keep our copy of EventDistpacher), we stay more closely aligned with three/examples events, and (unless people updated very very recently) it means no changes at all for them or our APIs.

**Pull request merged**
