### PR TITLE
fix(GLTFLoader): upstream with three

### PR DESCRIPTION
**Pull request by CodyJasonBennett**
Resolves https://github.com/pmndrs/react-three-fiber/issues/2848 by updating `GLTFLoader` with three.js.

### CODE REVIEW

**Comment by makc** [comment]
lol. @CodyJasonBennett does this mean that three-stdlib can no longer work with older three.js 🥲

**Comment by makc** [comment]
package.json still says
```json
  "peerDependencies": {
    "three": ">=0.122.0"
  }
  ```
  🥲

**Comment by CodyJasonBennett** [comment]
That's not what this PR does. I routinely mirror fixes here as I make them in three.js but it has no unusual implications on semver.

**Comment by makc** [comment]
@CodyJasonBennett I was under impression that the new loader makes uv1 where the old one used to make uv2. This sounds like something that would have implications on semver to me 🤷

**Pull request merged**
