### PR TITLE
fix: BufferGeometry rename uv2 to uv1

### PR DESCRIPTION
**Pull request by RodrigoHamuy**
`uv2` has been renamed to `uv1` in `threejs`: https://github.com/mrdoob/three.js/pull/25943

### CODE REVIEW

**Comment by CodyJasonBennett** [comment]
We'll need to perform some indirection here for the key to preserve backward compatibility. Had a tough time maintaining this with the back-to-back renames between versions.

https://github.com/pmndrs/three-stdlib/blob/d89e3c32a1eb97e9415e2c361e18af081bc66a25/src/loaders/GLTFLoader.js#L1753-L1770

**Comment by RodrigoHamuy** [comment]
@CodyJasonBennett I believe `GLTFLoader.js` is already up to date with backward compatibility in mind. 

Would you prefer if I update my changes to follow the same strategy, or shall we ditch backward compatibility in this case? I think is not a terrible idea to ask users to update to a ThreeJS version that is more than a year old already.

**Comment by CodyJasonBennett** [comment]
The goal of this project is to make itself obsolete by fostering improvements to three examples, and upstreaming them, but we have the additional constraint of adhering to SemVer (which I personally think is an oversight) which means we have to employ tricks to maintain compatibility.

Requiring an upgrade to three.js is a breaking change (major version increment), and I think we can try to maintain an indirection table until that becomes infeasible. The need for an upgrade to three.js is a larger conversation than the changes in this PR alone, as we support as low as r128 with many breaking changes to public API and types since.

**Comment by CodyJasonBennett** [comment]
I can do this myself in a few hours, when I can take a closer look.

**Comment by RodrigoHamuy** [comment]
@CodyJasonBennett backward compatibility added ☺️

**Comment by CodyJasonBennett** [comment]
Thanks; I appreciate the thoroughness. Elevating to a fix so we can get this out.

**Pull request merged**
