### PR TITLE
fix(MeshoptDecoder): allow tree-shaking, cleanup

### PR DESCRIPTION
**Pull request by CodyJasonBennett**
### Why

MeshoptDecoder will bundle itself automatically and emit unwanted warnings when using SIMD. This has since landed in Node 16.4.0 and seems unnecessary to start (available since Chrome 91, Firefox 89, etc.).

### What

I've removed the IIFE and the warning as well as refactored it to ES6.

### Checklist

- [ ] Documentation updated
- [ ] Storybook entry added
- [x] Ready to be merged

### CODE REVIEW

**Comment by drcmda** [comment]
this is not enough, it's worse than the warning, it will actually inline meshopt wasm into your bundle, if you use it or not. this is because it's being executed as a IIFE. could you remove it and instance it on demand (in drei, i guess)?

**Comment by CodyJasonBennett** [comment]
Pardon my ignorance, but do you want me to inline this into Drei? I'm not too familiar with its usage within three.

**Comment by drcmda** [comment]
> Pardon my ignorance, but do you want me to inline this into Drei? I'm not too familiar with its usage within three.

the IIFE is here: https://github.com/pmndrs/three-stdlib/blob/main/src/libs/MeshoptDecoder.js#L229

this is what is preventing the bundler from tree shaking it out, because it's executed in global space

and here's where we use it in drei: https://github.com/pmndrs/drei/blob/master/src/core/useGLTF.tsx#L17

the solution has to remove the IIFE and make it so that it's being created when needed, but only once

**Comment by CodyJasonBennett** [comment]
I see, so something like this should pass without issue?

```js
let generated

const MeshoptDecoder = () => {
  if (generated) return generated

  generated = // wasm stuff

  return generated
}
```

**Comment by drcmda** [comment]
looks good to me

**Pull request merged**
